version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./laravel:/data
            - ./nginx/etc/laravel-app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
    laravel-app:
        build: ./laravel
        volumes:
            - ./laravel:/data
        command: bash -c 'if [ ! -d /data/app ];then composer create-project --prefer-dist laravel/laravel app "5.6.*";else cd app && composer install;fi; php-fpm'
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
